order/food/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

order/food/food/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('foodapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/food/foodapp/urls.py
from django.urls import path
from . import views

app_name="foodapp"
urlpatterns=[
    path('',views.allProdcat,name='allProdcat'),
    path('<slug:c_slug>/',views.allProdcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.catdetail, name='catdetail')

]

order/food/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

order/food/cart/models.py
from django.db import models
from foodapp.models import product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    Product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.Product.price*self.quantity

    def __str__(self):
        return self.Product

order/food/foodapp/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse("foodapp:products_by_category", args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='product', blank=True)
    Category = models.ForeignKey(category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_created=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse("foodapp:catdetail",args=[self.Category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

order/food/search_app/models.py
from django.db import models

# Create your models here.

order/food/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from foodapp.models import product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    Product = product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(Product=Product, cart=cart)
        if cart_item.quantity < cart_item.Product.stock:
            cart_item.quantity += 1
        cart_item.save();
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(Product=Product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.Product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(Product=Product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(Product=Product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

order/food/foodapp/views.py
from django.shortcuts import render, get_object_or_404
from foodapp.models import category, product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def allProdcat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(category, slug=c_slug)
        products_list = product.objects.filter(Category=c_page, available=True)
    else:
        products_list = product.objects.all().filter(available=True)
        paginator = Paginator(products_list, 3)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            products_list=paginator.page(page)
        except (EmptyPage,InvalidPage):
            products_list=paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category': c_page, 'products': products_list})


def catdetail(request, c_slug, product_slug):
    try:
        pro = product.objects.get(Category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'pro': pro})

order/food/search_app/views.py
from django.shortcuts import render
from foodapp.models import product
from django.db.models import Q

def searchResult(request):
    query=request.GET.get('q')
    if query is not None:
        products=product.objects.filter(Q(name__contains=query))
        return render(request,"search.html",{'query':query, 'products':products})

order/food/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

order/food/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
         Welcome to FOODIE.
{% endblock %}
{% block title %}
    Cart - order Your Favourite !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <h1 class="text-center my_title">
            Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'foodapp:allProdcat' %}">Here</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="tect-center">
        <br>
        <h1 class="text-center my_title">
            Your order cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.Product.get_absolute_url"><img src="{{cart_item.Product.img.url}}" class="float-left-rounded custom_image" style="width:50px;height:50px;"></a>
                </td>
                <td class="text-lef">
                    {{cart_item.Product.name}}
                    <br>
                    SKU : {{cart_item.product.id}}
                    <br>
                    Unit price : ₹{{cart_item.Product.price}}
                    QTY : {{cart_item.quantity}} X ₹{{cart_item.Product.price}}
                </td>
                <td>₹{{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.Product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.Product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.Product.id %}"><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.Product.id %}"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' cart_item.Product.id %}"><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.Product.id %}"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your order cart items before proceeding with the order payement.
                </td>
            </tr>
            <tr>
                <td class="text-lef">
                Your total is <strong>₹{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'foodapp:allProdcat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div><br>
{% endif %}
{% endblock %}

order/food/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
         {{category.desc |truncatewords:150}}
    {% else %}
         Welcome to FOODIEE.
    {% endif %}

{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-FOODIE Order cart
    {% else %}
        Hungry! we are here.
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p>{{category.name}}</p>
            </div>
        </div>
    {% endif %}
<div>
    {% if category %}
        <img src="{{category.img.url}}" alt="{{category.name}}" style="height:336px; width:280px;">
</div><br>
<div>
    <h1>{{category.name}}</h1>
    <p>{{category.desc}}</p>
</div>
    {% else %}
        <div>
           <center><img src="{% static 'img/baner.png' %}" alt="" style="height:400px; width:1349px;"></center>
        </div><br>
        <div>
            <h1>Food Items</h1>
        </div>
    {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="width: 18rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}" style="height:336px; width:280px;"></a>
                    <div>
                        <h4>{{product.name}}</h4>
                        <p>₹{{product.price}}</p><br>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
     <div class="mx-auto">
         <div class="text-center">
             {% for pg in products.paginator.page_range %}
             <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
             {% endfor %}
         </div>
    </div>
</div>
{% endblock %}

order/food/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; FOODIE. All Rights Reserved</p>
</div>

order/food/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">About us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'foodapp:allProdcat' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'foodapp:allProdcat' %}">All Food Items</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-cart-plus">{{item_count}}</i></a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

order/food/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc | truncatewords:150}}
{% endblock %}
{% block title %}
    {{product.name}}-FOODIE order cart
{% endblock %}
{% block content %}
<div class="row my_product_row_class">
    <div class="mx-auto">
        <p><a href="{{product.name.category.get.url }}"></a>{{product.name}}</p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:18rem;">
                <img src="{{pro.img.url}}" alt="{{pro.name}}" style="height:336px; width:280px;">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_pro_title">{{pro.name}}</h1>
                <p>₹{{pro.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_pro_text">{{pro.desc}}</p>
                {% if pro.stock  <= 0 %}
                    <p class="text-justify my_pro_text"><b> Out of stock</b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' pro.id %}">Add to cart</a>
                {% endif %}
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

order/food/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc | truncatewords:150}}
{% endblock %}
{% block title %}
    {{product.name}}-FOODIE Order Cart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">search result for: {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="width: 18rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}" style="height:336px; width:280px;"></a>
                    <div>
                        <h4>{{product.name}}</h4>
                        <p>₹{{product.price}}</p><br>
                    </div>
                </div>
            </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}